"""
Seed scraper: hardcoded known programs.

This is the FALLBACK that guarantees data even if all web scrapers fail.
Based on verified research (June 2026). Update monthly.
"""
from utils.models import CreditProgram
from rich.console import Console

console = Console()
SOURCE = "seed_data"


SEED_PROGRAMS = [
    # ── CLOUD INFRA ──────────────────────────────────────────────────────────
    CreditProgram("AWS", "AWS Activate – Founders", "☁️ Cloud Infra",
                  "$1,000", "1 year", "Any registered startup, no VC needed",
                  "No", "https://aws.amazon.com/activate/",
                  "Entry tier. Apply day 1.", SOURCE),
    CreditProgram("AWS", "AWS Activate – Portfolio", "☁️ Cloud Infra",
                  "$25,000–$100,000", "2 years", "VC/accelerator-backed or AWS partner",
                  "Yes (or Partner)", "https://aws.amazon.com/activate/",
                  "Covers Bedrock (Claude, Llama). Stack with NVIDIA Inception.", SOURCE),
    CreditProgram("AWS", "AWS Generative AI Tier", "☁️ Cloud Infra",
                  "Up to $300,000", "2 years", "AI-native startup, accelerator preferred",
                  "Yes", "https://aws.amazon.com/activate/",
                  "Highest AWS tier. Mention production call volume.", SOURCE),
    CreditProgram("Microsoft", "Founders Hub – Baseline", "☁️ Cloud Infra",
                  "$1,000–$5,000", "12 months", "Any startup, no VC required",
                  "No", "https://www.microsoft.com/en-us/startups",
                  "Self-serve. Takes 10 min. Best no-VC cloud option.", SOURCE),
    CreditProgram("Microsoft", "Founders Hub – Scale", "☁️ Cloud Infra",
                  "Up to $150,000", "24 months", "Seed/Series A with traction",
                  "Preferred", "https://www.microsoft.com/en-us/startups",
                  "Includes GitHub Enterprise 20 seats + Azure OpenAI.", SOURCE),
    CreditProgram("Google", "Google for Startups Cloud – Standard", "☁️ Cloud Infra",
                  "$1,000–$100,000", "2 years", "Pre-seed/seed, under $1M raised",
                  "No (lower tiers)", "https://cloud.google.com/startup",
                  "Covers Vertex AI / Gemini. Mention Indian market.", SOURCE),
    CreditProgram("Google", "Google for Startups – AI-First", "☁️ Cloud Infra",
                  "Up to $350,000", "2 years", "YC/Techstars/accelerator backed",
                  "Yes", "https://cloud.google.com/startup",
                  "Highest GCP tier. Apply via accelerator.", SOURCE),
    CreditProgram("DigitalOcean", "Hatch Program", "☁️ Cloud Infra",
                  "Up to $100,000", "12 months", "Early-stage, under $5M raised",
                  "No", "https://www.digitalocean.com/hatch",
                  "$10K/month cap. Easy approval. No VC needed.", SOURCE),
    CreditProgram("Cloudflare", "Cloudflare for Startups", "☁️ Cloud Infra",
                  "$5,000–$250,000", "12 months", "Stage-dependent, bootstrapped qualifies",
                  "No (base)", "https://www.cloudflare.com/forstartups/",
                  "CDN, Workers, R2. Hard 1-year expiry.", SOURCE),
    CreditProgram("IBM", "IBM for Startups", "☁️ Cloud Infra",
                  "Up to $120,000", "12 months", "AI/ML startup, early-stage",
                  "No", "https://developer.ibm.com/startups/",
                  "Less competition = easier approval.", SOURCE),

    # ── AI / LLM ─────────────────────────────────────────────────────────────
    CreditProgram("Anthropic", "Claude for Startups – Standard", "🤖 AI / LLM",
                  "$25,000+", "12 months", "AI-native startup, company domain email",
                  "No (traction helps)", "https://www.anthropic.com/startups",
                  "Priority rate limits + early model access. CRITICAL for voice AI stack.", SOURCE),
    CreditProgram("Anthropic", "Claude for Startups – VC/Partner", "🤖 AI / LLM",
                  "$25,000–$100,000+", "12 months", "VC-backed or Anthropic partner accelerator",
                  "Yes", "https://www.anthropic.com/startups",
                  "Higher tier via accelerator Anthropic partner code.", SOURCE),
    CreditProgram("OpenAI", "OpenAI for Startups (via Ramp)", "🤖 AI / LLM",
                  "$2,500–$5,000", "12 months", "Pre-revenue to seed via Ramp corporate card",
                  "No", "https://openai.com/for-startups",
                  "One grant per org. Cannot stack multiple grants on same org.", SOURCE),
    CreditProgram("OpenAI", "OpenAI Grove Cohort", "🤖 AI / LLM",
                  "$50,000", "Program duration", "Any founder; SF in-person required",
                  "No", "https://openai.com/index/openai-grove/",
                  "5-week SF cohort. Investor intros included.", SOURCE),
    CreditProgram("Mistral", "Mistral for Startups", "🤖 AI / LLM",
                  "$1,000–$5,000", "12 months", "Any early-stage startup",
                  "No", "https://mistral.ai/",
                  "Fast European LLM. Good multilingual fallback.", SOURCE),
    CreditProgram("Together AI", "Together AI Startup Program", "🤖 AI / LLM",
                  "$1,000–$25,000", "12 months", "Pre-seed to Series A, no VC required",
                  "No", "https://www.together.ai/startups",
                  "Open-weight inference (Llama, DeepSeek). Cheapest per-token.", SOURCE),
    CreditProgram("Perplexity", "Perplexity Startup Program", "🤖 AI / LLM",
                  "$5,000", "Varies", "Early-stage startup",
                  "No", "https://www.perplexity.ai/",
                  "Real-time web search API.", SOURCE),
    CreditProgram("Cohere", "Cohere for AI", "🤖 AI / LLM",
                  "Varies", "12 months", "AI startup building with embeddings/RAG",
                  "No", "https://cohere.com/",
                  "Strong for embeddings. Less competition.", SOURCE),

    # ── VOICE / STT/TTS ──────────────────────────────────────────────────────
    CreditProgram("Deepgram", "Deepgram Startup Program", "🎙️ Voice / STT/TTS",
                  "Up to $100,000", "12 months", "Early-stage, building with voice/speech",
                  "No", "https://deepgram.com/startup-program",
                  "Core STT/TTS stack. ~1 week review. Mention production call volume.", SOURCE),
    CreditProgram("AssemblyAI", "AssemblyAI Startup Program", "🎙️ Voice / STT/TTS",
                  "$10,000–$50,000", "12 months", "Startup building speech/audio product",
                  "No", "https://www.assemblyai.com/",
                  "Strong for diarisation, sentiment, Hindi transcription.", SOURCE),
    CreditProgram("ElevenLabs", "ElevenLabs Grants Program", "🎙️ Voice / STT/TTS",
                  "33M chars (~$4,000+)", "12 months", "Startup with <25 employees",
                  "No", "https://elevenlabs.io/grants",
                  "680+ hours audio. For HNI/demo calls.", SOURCE),
    CreditProgram("Sarvam AI", "Sarvam Samvaad Partner Credits", "🎙️ Voice / STT/TTS",
                  "TBD – program launching", "12 months",
                  "Indian voice AI startup; direct outreach preferred",
                  "No", "https://www.sarvam.ai/",
                  "Public launch imminent June 2026. Contact team directly.", SOURCE),

    # ── DEV TOOLS ────────────────────────────────────────────────────────────
    CreditProgram("NVIDIA", "NVIDIA Inception Program", "🖥️ GPU / Hardware",
                  "Free (unlocks $250K+ in partner credits)", "Ongoing",
                  "AI/ML startup, any stage, no VC required",
                  "No", "https://www.nvidia.com/en-us/startups/",
                  "FREE. Master key. Join FIRST — unlocks AWS Portfolio + Nebius $150K.", SOURCE),
    CreditProgram("GitHub", "GitHub for Startups", "🛠️ Dev Tools",
                  "20 seats GitHub Enterprise free", "12 months",
                  "Startup via VC/accelerator/incubator affiliation",
                  "Yes (partner)", "https://github.com/solutions/startups",
                  "Free CI/CD, Copilot Business, Actions minutes.", SOURCE),
    CreditProgram("Datadog", "Datadog for Startups", "🛠️ Dev Tools",
                  "Up to $100,000 (1 year Pro)", "12 months", "Early-stage startup",
                  "No", "https://www.datadoghq.com/startups/",
                  "Full-stack monitoring. Critical for production voice AI.", SOURCE),
    CreditProgram("Retool", "Retool Startup Program", "🛠️ Dev Tools",
                  "Up to $60,000", "1 year + discounted Y2", "Early-stage startup",
                  "No", "https://retool.com/startups",
                  "Internal ops dashboards for call monitoring.", SOURCE),
    CreditProgram("Supabase", "Supabase for Startups", "🛠️ Dev Tools",
                  "$1,000–$10,000", "12 months", "Any startup, no VC required",
                  "No", "https://supabase.com/startups",
                  "Postgres + Vector DB + Auth. Relevant for call analytics.", SOURCE),
    CreditProgram("MongoDB", "MongoDB for Startups", "🛠️ Dev Tools",
                  "Up to $20,000", "12 months", "Not on paid MongoDB plan previously",
                  "No", "https://www.mongodb.com/startups",
                  "One-time grant. Apply when you'll actually use it.", SOURCE),
    CreditProgram("Notion", "Notion for Startups", "🛠️ Dev Tools",
                  "6 months free Business (~$500)", "6 months", "Any startup; one-time only",
                  "No", "https://www.notion.so/startups",
                  "One redemption ever. Claim via Stripe Atlas or direct.", SOURCE),
    CreditProgram("Vercel", "Vercel for Startups", "🛠️ Dev Tools",
                  "Vercel Pro + platform credits", "12 months",
                  "Early-stage via accelerator/VC referral",
                  "Yes (partner)", "https://vercel.com/solutions/startups",
                  "Hobby plan prohibits commercial use. Upgrade via startup program.", SOURCE),

    # ── CRM / GROWTH ─────────────────────────────────────────────────────────
    CreditProgram("HubSpot", "HubSpot for Startups", "📈 CRM / Growth",
                  "Up to 90% off Year 1", "3 years", "Seed-stage, under $2M raised",
                  "No", "https://www.hubspot.com/startups",
                  "Full CRM + marketing automation.", SOURCE),

    # ── FINTECH / MISC ────────────────────────────────────────────────────────
    CreditProgram("Stripe", "Stripe Atlas + Partner Perks", "🏦 Fintech / Misc",
                  "$150 off + $100K+ in partner credits", "Varies",
                  "Any startup incorporating globally",
                  "No", "https://stripe.com/atlas",
                  "Incorporation aggregator. Unlocks AWS, Notion, OpenAI credits.", SOURCE),
    CreditProgram("Ramp", "Ramp Founder Stack", "🏦 Fintech / Misc",
                  "$5,000 OpenAI + other credits", "12 months",
                  "Any startup with business bank account",
                  "No", "https://ramp.com/perks",
                  "Corporate card bundling OpenAI $5K + other SaaS.", SOURCE),
    CreditProgram("Brex", "Brex Startup Perks", "🏦 Fintech / Misc",
                  "$100K+ bundled", "Varies", "Registered startup",
                  "No", "https://www.brex.com/startups",
                  "Corporate card bundling AWS, GCP, Stripe and more.", SOURCE),
]


def scrape() -> list[CreditProgram]:
    console.print(f"[cyan]Loading seed data ({len(SEED_PROGRAMS)} verified programs)...[/cyan]")
    return list(SEED_PROGRAMS)
